# SkinCanserClassification

Bu projede deri kanserini algilayan bir CNN modeli gelistirecegiz. Model kaydedip streamlit uygulamasina cevirecegiz ve huggingface'de calisir hale getirecegiz.

In [17]:
import cv2
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Conv2D,Dense, Flatten, Input, MaxPooling2D, Dropout, BatchNormalization, Reshape
import os

In [22]:
labels=['Cancer','Non_Cancer']

In [23]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 08D6-2CCE

 Directory of C:\Users\kosey\OneDrive\Documents\GitHub\ai_course\Day12

09.11.2025  10:27    <DIR>          .
09.11.2025  06:59    <DIR>          ..
09.11.2025  10:13    <DIR>          .ipynb_checkpoints
09.11.2025  09:32             3.074 app.py
09.11.2025  08:12           141.824 cars.xls
09.11.2025  09:32            51.005 cars.xlsx
09.11.2025  10:04    <DIR>          Skin_Data
09.11.2025  10:27             4.698 SkinCanserClassification.ipynb
               4 File(s)        200.601 bytes
               4 Dir(s)  387.137.196.032 bytes free

In [24]:
img_path='Skin_Data/'

In [25]:
img_list=[]
label_list=[]
for label in labels:
    for img_file in os.listdir(img_path+label):
        img_list.append(img_path+label+"/"+img_file)
        label_list.append(label)

In [26]:
df=pd.DataFrame({'img':img_list,'label':label_list})

In [27]:
df

                                 img       label
0        Skin_Data/Cancer/1007-1.jpg      Cancer
1       Skin_Data/Cancer/1010-01.JPG      Cancer
2        Skin_Data/Cancer/1012-2.JPG      Cancer
3        Skin_Data/Cancer/1031-1.jpg      Cancer
4    Skin_Data/Cancer/1051-3(94).jpg      Cancer
..                               ...         ...
283   Skin_Data/Non_Cancer/953-1.JPG  Non_Cancer
284   Skin_Data/Non_Cancer/954-3.JPG  Non_Cancer
285     Skin_Data/Non_Cancer/955.JPG  Non_Cancer
286     Skin_Data/Non_Cancer/984.JPG  Non_Cancer
287   Skin_Data/Non_Cancer/986-1.JPG  Non_Cancer

[288 rows x 2 columns]

In [29]:
d=({'Cancer':1, 'Non_Cancer':0})
df['label_encoded']=df['label'].map(d)

In [30]:
df

                                 img       label  label_encoded
0        Skin_Data/Cancer/1007-1.jpg      Cancer              1
1       Skin_Data/Cancer/1010-01.JPG      Cancer              1
2        Skin_Data/Cancer/1012-2.JPG      Cancer              1
3        Skin_Data/Cancer/1031-1.jpg      Cancer              1
4    Skin_Data/Cancer/1051-3(94).jpg      Cancer              1
..                               ...         ...            ...
283   Skin_Data/Non_Cancer/953-1.JPG  Non_Cancer              0
284   Skin_Data/Non_Cancer/954-3.JPG  Non_Cancer              0
285     Skin_Data/Non_Cancer/955.JPG  Non_Cancer              0
286     Skin_Data/Non_Cancer/984.JPG  Non_Cancer              0
287   Skin_Data/Non_Cancer/986-1.JPG  Non_Cancer              0

[288 rows x 3 columns]

In [32]:
x=[]
for img in df['img']:
    img=cv2.imread(str(img))
    img=cv2.resize(img,(170,170))
    img=img/255.0 # normalize et
    x.append(img)

In [33]:
x=np.array(x)

In [34]:
x.shape

(288, 170, 170, 3)

In [35]:
x

array([[[[0.69411765, 0.74901961, 0.95686275],
         [0.6745098 , 0.72941176, 0.9372549 ],
         [0.59607843, 0.64313725, 0.8627451 ],
         ...,
         [0.49411765, 0.62745098, 0.84705882],
         [0.49411765, 0.63137255, 0.85098039],
         [0.51372549, 0.64313725, 0.8627451 ]],

        [[0.63921569, 0.69411765, 0.88627451],
         [0.64313725, 0.69803922, 0.90196078],
         [0.63529412, 0.69803922, 0.90588235],
         ...,
         [0.52156863, 0.63137255, 0.84705882],
         [0.5254902 , 0.63921569, 0.85490196],
         [0.5372549 , 0.64313725, 0.8627451 ]],

        [[0.64313725, 0.70588235, 0.89803922],
         [0.65882353, 0.71372549, 0.91764706],
         [0.64313725, 0.70980392, 0.91372549],
         ...,
         [0.54117647, 0.64705882, 0.86666667],
         [0.56078431, 0.66666667, 0.88627451],
         [0.5372549 , 0.64705882, 0.8627451 ]],

        ...,

        [[0.64313725, 0.74117647, 0.9372549 ],
         [0.62745098, 0.72156863, 0.91764706],
         [0.62745098, 0.71764706, 0.90588235],
         ...,
         [0.72156863, 0.81960784, 0.95294118],
         [0.69019608, 0.78823529, 0.92156863],
         [0.66666667, 0.76078431, 0.90196078]],

        [[0.69411765, 0.78823529, 0.96470588],
         [0.71764706, 0.81176471, 0.99215686],
         [0.69019608, 0.78039216, 0.95686275],
         ...,
         [0.68235294, 0.78039216, 0.92156863],
         [0.64313725, 0.74509804, 0.88627451],
         [0.70980392, 0.81960784, 0.95686275]],

        [[0.6627451 , 0.77254902, 0.93333333],
         [0.69803922, 0.79607843, 0.96078431],
         [0.69803922, 0.78431373, 0.94509804],
         ...,
         [0.61568627, 0.72941176, 0.88235294],
         [0.60784314, 0.72941176, 0.88235294],
         [0.64313725, 0.77254902, 0.9254902 ]]],


       [[[0.11372549, 0.1372549 , 0.21176471],
         [0.11372549, 0.1372549 , 0.21176471],
         [0.23137255, 0.25490196, 0.32941176],
         ...,
         [0.14901961, 0.20392157, 0.36862745],
         [0.10588235, 0.16470588, 0.34509804],
         [0.06666667, 0.11372549, 0.30196078]],

        [[0.11764706, 0.14509804, 0.21176471],
         [0.12941176, 0.15294118, 0.22352941],
         [0.29411765, 0.31764706, 0.38823529],
         ...,
         [0.09803922, 0.16078431, 0.30980392],
         [0.01568627, 0.08235294, 0.24313725],
         [0.07843137, 0.12941176, 0.29803922]],

        [[0.12941176, 0.14509804, 0.21568627],
         [0.17647059, 0.20392157, 0.27058824],
         [0.14509804, 0.17647059, 0.24313725],
         ...,
         [0.06666667, 0.12941176, 0.2745098 ],
         [0.08627451, 0.14901961, 0.31372549],
         [0.14509804, 0.19607843, 0.36862745]],

        ...,

        [[0.10980392, 0.1254902 , 0.23529412],
         [0.0627451 , 0.08627451, 0.1372549 ],
         [0.05098039, 0.0745098 , 0.11764706],
         ...,
         [0.16078431, 0.25490196, 0.45882353],
         [0.17254902, 0.26666667, 0.47058824],
         [0.15294118, 0.24705882, 0.45882353]],

        [[0.09411765, 0.10980392, 0.21960784],
         [0.07058824, 0.10196078, 0.15294118],
         [0.07843137, 0.10196078, 0.14509804],
         ...,
         [0.14509804, 0.25098039, 0.45490196],
         [0.15686275, 0.25882353, 0.47058824],
         [0.14509804, 0.24313725, 0.45882353]],

        [[0.09411765, 0.11764706, 0.21568627],
         [0.08627451, 0.10980392, 0.16078431],
         [0.07843137, 0.09803922, 0.15686275],
         ...,
         [0.15686275, 0.2627451 , 0.4627451 ],
         [0.14901961, 0.2627451 , 0.4627451 ],
         [0.14117647, 0.24705882, 0.46666667]]],


       [[[0.29411765, 0.44313725, 0.65490196],
         [0.28627451, 0.43921569, 0.64313725],
         [0.30588235, 0.45882353, 0.6627451 ],
         ...,
         [0.30196078, 0.41568627, 0.6       ],
         [0.30980392, 0.42352941, 0.6       ],
         [0.29019608, 0.40784314, 0.59215686]],

        [[0.29411765, 0.44313725, 0.65490196],
         [0.30196078, 0.45098039, 0.6627451 ],
         [0.30196078, 0.45098039, 0.6627451 ],
         ...,
         [0.30588235, 0.41960784, 0.60784314],
         [0.31372549, 0.42352941, 0.60784314],
         [0.30196078, 0.41176471, 0.58823529]],

        [[0.29803922, 0.44705882, 0.66666667],
         [0.30588235, 0.45490196, 0.66666667],
         [0.28627451, 0.43529412, 0.64705882],
         ...,
         [0.30980392, 0.41960784, 0.60392157],
         [0.30196078, 0.41176471, 0.59607843],
         [0.30980392, 0.41176471, 0.59215686]],

        ...,

        [[0.38431373, 0.52941176, 0.7254902 ],
         [0.36470588, 0.50980392, 0.70588235],
         [0.37254902, 0.51764706, 0.71372549],
         ...,
         [0.36470588, 0.50588235, 0.69411765],
         [0.36862745, 0.50980392, 0.69803922],
         [0.36470588, 0.50588235, 0.69411765]],

        [[0.37254902, 0.5254902 , 0.72941176],
         [0.36862745, 0.51372549, 0.70980392],
         [0.38823529, 0.53333333, 0.72941176],
         ...,
         [0.37254902, 0.51372549, 0.70196078],
         [0.36862745, 0.50980392, 0.69803922],
         [0.35686275, 0.50588235, 0.69411765]],

        [[0.38823529, 0.53333333, 0.72941176],
         [0.40392157, 0.54117647, 0.7372549 ],
         [0.41960784, 0.56078431, 0.74901961],
         ...,
         [0.36862745, 0.50980392, 0.69803922],
         [0.36862745, 0.50980392, 0.69803922],
         [0.36078431, 0.50980392, 0.69803922]]],


       ...,


       [[[0.13333333, 0.18431373, 0.36470588],
         [0.1254902 , 0.17647059, 0.35686275],
         [0.11764706, 0.16862745, 0.34901961],
         ...,
         [0.14117647, 0.19215686, 0.38039216],
         [0.1372549 , 0.18431373, 0.37254902],
         [0.14901961, 0.19607843, 0.38431373]],

        [[0.12156863, 0.17254902, 0.35294118],
         [0.12156863, 0.17254902, 0.35294118],
         [0.12156863, 0.17254902, 0.35294118],
         ...,
         [0.14509804, 0.19607843, 0.38431373],
         [0.14509804, 0.19215686, 0.38039216],
         [0.14901961, 0.19607843, 0.38431373]],

        [[0.11764706, 0.16862745, 0.34901961],
         [0.12156863, 0.17254902, 0.35294118],
         [0.12156863, 0.17647059, 0.35686275],
         ...,
         [0.14117647, 0.19607843, 0.38823529],
         [0.14509804, 0.19607843, 0.38823529],
         [0.14117647, 0.19215686, 0.38431373]],

        ...,

        [[0.15686275, 0.21568627, 0.36862745],
         [0.14509804, 0.20392157, 0.35686275],
         [0.12941176, 0.18431373, 0.34901961],
         ...,
         [0.1372549 , 0.2       , 0.36862745],
         [0.1372549 , 0.19607843, 0.37647059],
         [0.14117647, 0.2       , 0.38039216]],

        [[0.14509804, 0.20392157, 0.35686275],
         [0.14117647, 0.19607843, 0.35294118],
         [0.1254902 , 0.18039216, 0.34509804],
         ...,
         [0.14117647, 0.20392157, 0.37254902],
         [0.1372549 , 0.19607843, 0.37647059],
         [0.14117647, 0.2       , 0.38039216]],

        [[0.13333333, 0.19215686, 0.34509804],
         [0.12941176, 0.18823529, 0.34117647],
         [0.11764706, 0.17254902, 0.3372549 ],
         ...,
         [0.14509804, 0.20784314, 0.37647059],
         [0.14117647, 0.2       , 0.38039216],
         [0.14509804, 0.20392157, 0.38431373]]],


       [[[0.42745098, 0.54509804, 0.72941176],
         [0.38431373, 0.49803922, 0.67843137],
         [0.37254902, 0.48627451, 0.6627451 ],
         ...,
         [0.43137255, 0.52941176, 0.69803922],
         [0.43529412, 0.53333333, 0.69803922],
         [0.43137255, 0.52941176, 0.69411765]],

        [[0.41176471, 0.52941176, 0.70980392],
         [0.38431373, 0.49803922, 0.67843137],
         [0.35294118, 0.46666667, 0.63921569],
         ...,
         [0.41176471, 0.50980392, 0.6745098 ],
         [0.42352941, 0.52156863, 0.68627451],
         [0.42745098, 0.5254902 , 0.69019608]],

        [[0.38823529, 0.49803922, 0.6745098 ],
         [0.37254902, 0.47843137, 0.65490196],
         [0.3372549 , 0.44313725, 0.61568627],
         ...,
         [0.39215686, 0.49019608, 0.65490196],
         [0.40392157, 0.50196078, 0.66666667],
         [0.40784314, 0.50588235, 0.6745098 ]],

        ...,

        [[0.40392157, 0.49411765, 0.67058824],
         [0.41568627, 0.50980392, 0.68627451],
         [0.43529412, 0.53333333, 0.71372549],
         ...,
         [0.39215686, 0.49803922, 0.67058824],
         [0.39607843, 0.50196078, 0.6745098 ],
         [0.41176471, 0.51764706, 0.69019608]],

        [[0.43921569, 0.5254902 , 0.70196078],
         [0.47058824, 0.56078431, 0.7372549 ],
         [0.4627451 , 0.55686275, 0.7372549 ],
         ...,
         [0.4       , 0.50980392, 0.68235294],
         [0.39607843, 0.50588235, 0.68235294],
         [0.41176471, 0.52156863, 0.69411765]],

        [[0.44313725, 0.5254902 , 0.70196078],
         [0.49411765, 0.58039216, 0.75686275],
         [0.4745098 , 0.56470588, 0.74509804],
         ...,
         [0.41176471, 0.5254902 , 0.69803922],
         [0.4       , 0.51372549, 0.68627451],
         [0.40392157, 0.52156863, 0.69411765]]],


       [[[0.67843137, 0.74509804, 0.8745098 ],
         [0.68235294, 0.74901961, 0.87843137],
         [0.68235294, 0.74901961, 0.88235294],
         ...,
         [0.6627451 , 0.73333333, 0.8627451 ],
         [0.66666667, 0.73333333, 0.8627451 ],
         [0.66666667, 0.73333333, 0.8627451 ]],

        [[0.67058824, 0.7372549 , 0.86666667],
         [0.6745098 , 0.74117647, 0.87058824],
         [0.6745098 , 0.74509804, 0.8745098 ],
         ...,
         [0.6627451 , 0.72941176, 0.8627451 ],
         [0.66666667, 0.73333333, 0.8627451 ],
         [0.66666667, 0.73333333, 0.8627451 ]],

        [[0.65882353, 0.7254902 , 0.85490196],
         [0.65882353, 0.7254902 , 0.85490196],
         [0.65882353, 0.72941176, 0.8627451 ],
         ...,
         [0.65098039, 0.72156863, 0.85490196],
         [0.65490196, 0.7254902 , 0.8627451 ],
         [0.65490196, 0.7254902 , 0.8627451 ]],

        ...,

        [[0.67843137, 0.74117647, 0.84705882],
         [0.67843137, 0.74117647, 0.85098039],
         [0.67843137, 0.74117647, 0.85098039],
         ...,
         [0.69803922, 0.75686275, 0.86666667],
         [0.69803922, 0.75294118, 0.8627451 ],
         [0.69411765, 0.74901961, 0.85882353]],

        [[0.68627451, 0.74117647, 0.85098039],
         [0.69019608, 0.74509804, 0.85490196],
         [0.69019608, 0.74509804, 0.85490196],
         ...,
         [0.69803922, 0.75294118, 0.8627451 ],
         [0.69803922, 0.75294118, 0.8627451 ],
         [0.69411765, 0.74901961, 0.85882353]],

        [[0.69803922, 0.75294118, 0.8627451 ],
         [0.69803922, 0.75294118, 0.8627451 ],
         [0.69411765, 0.74901961, 0.85882353],
         ...,
         [0.69803922, 0.75294118, 0.8627451 ],
         [0.69411765, 0.74901961, 0.8627451 ],
         [0.69411765, 0.74901961, 0.85882353]]]])

In [46]:
y=df['label_encoded']

In [47]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20, random_state=42)

In [48]:
y_train=np.array(y_train, dtype=np.int32)
y_test=np.array(y_test, dtype=np.int32)

In [49]:
model=Sequential()
model.add(Input(shape=(170, 170, 3)))
model.add(Conv2D(32, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))  # Added activation function
model.add(Dense(1, activation='sigmoid'))  # Ensure 2 classes for binary classification

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [50]:
history=model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=20,verbose=1)

Epoch 1/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 3s 272ms/step - accuracy: 0.5696 - loss: 2.5446 - val_accuracy: 0.7414 - val_loss: 0.6747
Epoch 2/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 222ms/step - accuracy: 0.6043 - loss: 0.6870 - val_accuracy: 0.7414 - val_loss: 0.6070
Epoch 3/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 234ms/step - accuracy: 0.7087 - loss: 0.6624 - val_accuracy: 0.7414 - val_loss: 0.6125
Epoch 4/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 224ms/step - accuracy: 0.7087 - loss: 0.5823 - val_accuracy: 0.7414 - val_loss: 0.5743
Epoch 5/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 236ms/step - accuracy: 0.7348 - loss: 0.5453 - val_accuracy: 0.7069 - val_loss: 0.6153
Epoch 6/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 232ms/step - accuracy: 0.7739 - loss: 0.5110 - val_accuracy: 0.8103 - val_loss: 0.4823
Epoch 7/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 231ms/step - accuracy: 0.8348 - loss: 0.4144 - val_accuracy: 0.7414 - val_loss: 0.5323
Epoch 8/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 246ms/step - accuracy: 0.8522 - loss: 0.3616 - val_accuracy: 0.8448 - val_loss: 0.3684
Epoch 9/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 236ms/step - accuracy: 0.8478 - loss: 0.3572 - val_accuracy: 0.8103 - val_loss: 0.3918
Epoch 10/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 230ms/step - accuracy: 0.8565 - loss: 0.3113 - val_accuracy: 0.8621 - val_loss: 0.2985
Epoch 11/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 254ms/step - accuracy: 0.8609 - loss: 0.3188 - val_accuracy: 0.8621 - val_loss: 0.3699
Epoch 12/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 272ms/step - accuracy: 0.9000 - loss: 0.2378 - val_accuracy: 0.8621 - val_loss: 0.3317
Epoch 13/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 241ms/step - accuracy: 0.9435 - loss: 0.1849 - val_accuracy: 0.9138 - val_loss: 0.2818
Epoch 14/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 248ms/step - accuracy: 0.9348 - loss: 0.1649 - val_accuracy: 0.8448 - val_loss: 0.5300
Epoch 15/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 246ms/step - accuracy: 0.9304 - loss: 0.2262 - val_accuracy: 0.8276 - val_loss: 0.3578
Epoch 16/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 253ms/step - accuracy: 0.9261 - loss: 0.1599 - val_accuracy: 0.8966 - val_loss: 0.3072
Epoch 17/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 258ms/step - accuracy: 0.9739 - loss: 0.1209 - val_accuracy: 0.9138 - val_loss: 0.2365
Epoch 18/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 267ms/step - accuracy: 0.9739 - loss: 0.0787 - val_accuracy: 0.8448 - val_loss: 0.4336
Epoch 19/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 267ms/step - accuracy: 0.9522 - loss: 0.1193 - val_accuracy: 0.8966 - val_loss: 0.2014
Epoch 20/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 241ms/step - accuracy: 0.9652 - loss: 0.1045 - val_accuracy: 0.8621 - val_loss: 0.3182

In [ ]:
model.save('skin_cancer_model.h5')

In [53]:
model.save('skin_cancer_model.keras')

# Transfer Learning

Akilli insan aklini kullanir. Dahada akilli insan basklarinin aklini da kullanandir.

In [55]:
from tensorflow.keras.applications import VGG16, ResNet50
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [56]:
data_dir='Skin_Data'
img_width,img_heigth=224,224
train_datagen=ImageDataGenerator(rescale=1/255, validation_split=0.20)
train_datagenerator=train_datagen.flow_from_directory(directory=data_dir,target_size=(img_width,img_heigth),
                                class_mode='binary', subset='training')
test_datagen=ImageDataGenerator(rescale=1/255)
test_datagenerator=train_datagen.flow_from_directory(directory=data_dir,target_size=(img_width,img_heigth),
                                class_mode='binary', subset='validation')

# VGG16 hazir modeli cekiliyor
base_model=VGG16(weights='imagenet', input_shape=(img_width,img_heigth,3), include_top=False)

# Sequential yeni model olusturuluyor ve VGG16 modeli eklenoyor
model=Sequential()
model.add(base_model)
# hazir alinan VGG16 model icin ogrenmeyi kapatiyoruzki ogrenilmis model bozulmasin
for layer in base_model.layers:
    layer.trainable=False

# hazir ogrenilmis modelin ustune bizim goreseller ile tekrardan ogrenme yaptiriyoruz
model.add(Flatten())
model.add(Dense(1024,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

model.fit(train_datagenerator,epochs=10,validation_data=test_datagenerator)

Found 232 images belonging to 2 classes.
Found 56 images belonging to 2 classes.
Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/vgg16/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5
58889256/58889256 ━━━━━━━━━━━━━━━━━━━━ 11s 0us/step
Epoch 1/10

C:\Users\kosey\AppData\Roaming\Python\Python313\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()

8/8 ━━━━━━━━━━━━━━━━━━━━ 24s 3s/step - accuracy: 0.6207 - loss: 2.3288 - val_accuracy: 0.8571 - val_loss: 0.3488
Epoch 2/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 23s 3s/step - accuracy: 0.8664 - loss: 0.3091 - val_accuracy: 0.8214 - val_loss: 0.3400
Epoch 3/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 24s 3s/step - accuracy: 0.9440 - loss: 0.1607 - val_accuracy: 0.8393 - val_loss: 0.3653
Epoch 4/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 24s 3s/step - accuracy: 0.9741 - loss: 0.1057 - val_accuracy: 0.8214 - val_loss: 0.3469
Epoch 5/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 25s 3s/step - accuracy: 0.9914 - loss: 0.0779 - val_accuracy: 0.8214 - val_loss: 0.3313
Epoch 6/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 24s 3s/step - accuracy: 0.9871 - loss: 0.0667 - val_accuracy: 0.8214 - val_loss: 0.3336
Epoch 7/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 24s 3s/step - accuracy: 0.9871 - loss: 0.0680 - val_accuracy: 0.8393 - val_loss: 0.3800
Epoch 8/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 24s 3s/step - accuracy: 0.9828 - loss: 0.0556 - val_accuracy: 0.8393 - val_loss: 0.4025
Epoch 9/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 24s 3s/step - accuracy: 0.9957 - loss: 0.0424 - val_accuracy: 0.8393 - val_loss: 0.3243
Epoch 10/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 24s 3s/step - accuracy: 0.9828 - loss: 0.0400 - val_accuracy: 0.8036 - val_loss: 0.3178

In [57]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ vgg16 (Functional)              │ (None, 7, 7, 512)      │    14,714,688 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_2 (Flatten)             │ (None, 25088)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1024)           │    25,691,136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │         1,025 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 91,791,173 (350.16 MB)

 Trainable params: 25,692,161 (98.01 MB)

 Non-trainable params: 14,714,688 (56.13 MB)

 Optimizer params: 51,384,324 (196.02 MB)

In [58]:
model.save('tl_skin_cancer_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [59]:
model.save('tl_skin_cancer_model.keras')